[server]
headless = true

[browser]
gatherUsageStats = false

[global]
# Hide the "Made with Streamlit" footer and other branding
showWarningOnDirectExecution = false

[ui]
hideTopBar = true

[client]
toolbarMode = "viewer"

[theme]
primaryColor = "#0f62fe"  # IBM Carbon primary blue
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f4"
textColor = "#161616"